<?php use Framework\Renderer\View; ?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?php View::block('title') ?>Layout Title<?php View::close() ?></title>
</head>
<body>
<?php View::include('header.phtml') ?>

<?php View::block('content') ?>
    <main class="main">
        <h1>Layout Main</h1>
    </main>
<?php View::close() ?>

<p><?=View::format('Y-m-d H:i') ?></p>
</body>
</html>