<?php use Framework\Renderer\View; ?>

<header class="header">
    <div class="center header__content">
        <nav class="nav header__nav">
            <a href="<?= View::route('greeting') ?>" class="nav__a nav__logo">
                MY PHP FRAMEWORK
            </a>

            <div class="nav__link">
                <a href="<?= View::route('doc') ?>" class="nav__a">Documentation</a>
            </div>
        </nav>
    </div>
</header>
