<?php use Framework\Renderer\View; ?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My PHP Framework</title>
    <link rel="stylesheet" href="">
</head>
<body>

<?php View::block('main')?>
    <div class="main">
        Empty main
    </div>
<?php View::close()?>

</body>
</html>
